#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

function ensurePreCommitHook() {
  const gitDir = path.join(process.cwd(), '.git');
  const hooksDir = path.join(gitDir, 'hooks');
  const hookPath = path.join(hooksDir, 'pre-commit');

  if (!fs.existsSync(gitDir)) {
    console.log('No .git directory found; skipping hook install.');
    return;
  }

  fs.mkdirSync(hooksDir, { recursive: true });

  const content = `#!/bin/sh

# Auto-generated by scripts/install-hooks.js
# Pre-commit checks: dev sitemap, lint, type-check

if ! command -v npm >/dev/null 2>&1; then
  echo "[pre-commit] npm not found; skipping checks."
  exit 0
fi

# 1) Developer sitemap coverage
echo "[pre-commit] Verifying developer sitemap coverage..."
npm run --silent verify:dev-sitemap
status=$?
if [ $status -ne 0 ]; then
  echo "[pre-commit] Developer sitemap check failed. Commit aborted."
  exit $status
fi

# 2) ESLint
echo "[pre-commit] Running ESLint..."
npm run --silent lint
status=$?
if [ $status -ne 0 ]; then
  echo "[pre-commit] ESLint failed. Commit aborted."
  exit $status
fi

# 3) TypeScript type-check
echo "[pre-commit] Running TypeScript type-check..."
npm run --silent type-check
status=$?
if [ $status -ne 0 ]; then
  echo "[pre-commit] Type-check failed. Commit aborted."
  exit $status
fi

exit 0
`;

  fs.writeFileSync(hookPath, content, { encoding: 'utf8' });
  try {
    fs.chmodSync(hookPath, 0o755);
  } catch {}
  console.log('Installed pre-commit hook to .git/hooks/pre-commit');
}

ensurePreCommitHook();

